name: Deploy to VDS

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install sshpass
        run: sudo apt-get update && sudo apt-get install -y sshpass

      - name: Copy files to VDS
        run: |
          sshpass -p "${{ secrets.VDS_PASSWORD }}" scp -o StrictHostKeyChecking=no -r ./* ${{ secrets.VDS_USER }}@${{ secrets.VDS_HOST }}:/

      - name: Deploy with Docker Compose
        run: |
          sshpass -p "${{ secrets.VDS_PASSWORD }}" ssh -o StrictHostKeyChecking=no ${{ secrets.VDS_USER }}@${{ secrets.VDS_HOST }} "cd medusa && docker compose up --build -d"